### ISSUE TITLE
你好，请问您脚本中的网站有其他游戏的脚本爬取内容吗

### ISSUE THREAD

**Issue by scp23328** [SXK485/Flower-knight-girl-Viewer_update#1]
RT，大佬我想知道如天使链接R等游戏的H内容在您脚本中的网站中有吗？

**Comment by SXK485** [comment]
> RT，大佬我想知道如天使链接R等游戏的H内容在您脚本中的网站中有吗？

嗯，有一点要注意的是，我爬取的wiki，也就是fandom不包含任何H内容。我爬取它，仅仅是为了获取游戏的角色ID还有名字什么的。H内容相关的资源获取方法，比如图片、音频、剧本都是我先前已经知道的。对于其他游戏的资源获取方式，只能找一下有没有人做过，或是自己打开游戏分析。你可以在Eh上看看对应的游戏画廊评论，可能会找到一些有用的信息
